

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    jobs:
      - job: TerraformValidateJob   
        continueOnError: false
        steps:
                    
          - task: PublishBuildArtifacts@1
            displayName: publish artifacts
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              ArtifactName: 'terraform-manifests-out'
              publishLocation: 'Container'
          - task: TerraformInstaller@0
            displayName: Terraform Install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@0
            displayName: Terraform init
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              backendType: 'azurerm'
              backendServiceArm: 'Free Trial(1)(670a49a3-bea5-4729-aea5-8121cd918ca4)'
              backendAzureRmResourceGroupName: 'storage-rg'
              backendAzureRmStorageAccountName: 'koushiktanisha'
              backendAzureRmContainerName: 'tfstatefile'
              backendAzureRmKey: 'aks-terraform.tfstate'
              allowTelemetryCollection: false
          - task: TerraformCLI@0
            displayName: Terraform Validate
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              allowTelemetryCollection: false